### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by jubianchi** [atoum/bdd-extension#5]
We should have a license and it should be the same as the atoum/atoum repository
- [ ] a `LICENSE` file: it should be the same as the atoum/atoum repository but every mention to "Frédéric Hardy" must be replaced with "atoum contributors"
- [ ] in the `composer.json` file (`BSD-3-Clause`)
- [ ] in the  `README.md` file: a dedicated section (see [here](https://github.com/atoum/blackfire-extension/blob/master/README.md#licence) for an example)

**Comment by pjhampton** [comment]
Hey @jubianchi!!

I can add this in during Hacktoberfest 😄

**Comment by jubianchi** [comment]
@pjhampton ok, thanks!

**Comment by vonglasow** [comment]
Can we close this issue ? It looks merged.
